version: 2
jobs:
  stamp:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: sed -i "s/-dev/-${CIRCLE_BUILD_NUM}/g" package.json
      - run: printenv | grep NPM
      - run:  head -5 package.json
      - persist_to_workspace:
          root: ./
          paths:
            - package.json
  publish_develop:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: printenv | grep CIRCLE_BUILD_NUM
      - run: printenv | grep NPM
      - run:  head -5 package.json
      - run: ls -lt
      #- run: npm publish --tag dev --access public
  publish_master:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: printenv | grep NPM
      - run:  head -5 package.json
      #- run: npm publish --access public
workflows:
  version: 2
  publish:
    jobs:
      - stamp
      - publish_develop:
          requires:
            - stamp
          filters:
            branches:
              only: develop
      - publish_master:
          requires:
            - stamp
          filters:
            branches:
              only: master